# Basic
title: Wdream
subtitle: Personal Website
description: The Sky's The Limit.
# 头像里面的标题    
avatarTitle:
# 头像里面的描述
avatarDesc: (❁´◡`❁)
url: "https://violet-wdream.github.io"
backgroundUrl: '/images/background-cover.jpg'
# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726 
    github: violet-wdream
    bilibili: 439305206
    # zhihu: panpanleopard
    # juejin: xxx
    #jianshu: 2ada30d8d0f7
    # twitter: 
    mail: 2654887279@qq.com



# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id:
    host: auto  




permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Blog

# Navigation buttons in the front page.s
nav:
    - {title: Archives, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: Support, description: support, url: '/support'}      
    - {title: Anime Reviews, description: anime reviews, url: '/anime'}
    - {title: About Me, description: about, url: '/about'}
    - {title: Spine, description: spine, url: '/spine' }


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


